# Import dependencies

In [1]:
import polars_bio as pb
import pandas as pd
from polars_bio.range_viz import visualize_intervals

INFO:polars_bio:Creating BioSessionContext

# Import data

In [2]:
pb.read_fastq("../../tests/resources/example.fastq")

INFO:polars_bio:Table: example registered for path: ../../tests/resources/example.fastq

In [3]:
pb.sql("show tables").collect()

0rows [00:00, ?rows/s]

shape: (6, 4)
┌───────────────┬────────────────────┬─────────────┬────────────┐
│ table_catalog ┆ table_schema       ┆ table_name  ┆ table_type │
│ ---           ┆ ---                ┆ ---         ┆ ---        │
│ str           ┆ str                ┆ str         ┆ str        │
╞═══════════════╪════════════════════╪═════════════╪════════════╡
│ datafusion    ┆ public             ┆ example     ┆ BASE TABLE │
│ datafusion    ┆ information_schema ┆ tables      ┆ VIEW       │
│ datafusion    ┆ information_schema ┆ views       ┆ VIEW       │
│ datafusion    ┆ information_schema ┆ columns     ┆ VIEW       │
│ datafusion    ┆ information_schema ┆ df_settings ┆ VIEW       │
│ datafusion    ┆ information_schema ┆ schemata    ┆ VIEW       │
└───────────────┴────────────────────┴─────────────┴────────────┘

In [4]:
pb.sql("select * from example limit 10").collect()

0rows [00:00, ?rows/s]

shape: (10, 4)
┌───────────────┬───────────────────────────┬───────────────────────────┬──────────────────────────┐
│ name          ┆ description               ┆ sequence                  ┆ quality_scores           │
│ ---           ┆ ---                       ┆ ---                       ┆ ---                      │
│ str           ┆ str                       ┆ str                       ┆ str                      │
╞═══════════════╪═══════════════════════════╪═══════════════════════════╪══════════════════════════╡
│ SRR9130495.1  ┆ D00236:723:HG32CBCX2:1:11 ┆ NCAATACAAAAGCAATATGGGAGAA ┆ #4BDFDFFHGHGGJJJHIIIIGGI │
│               ┆ 08:13…                    ┆ GCTAC…                    ┆ IJGJJG…                  │
│ SRR9130495.2  ┆ D00236:723:HG32CBCX2:1:11 ┆ NGTCAAAGATAAGATCAAAAGGCAC ┆ #1=DDDDD>DHFH@EFHHGHGGFG │
│               ┆ 08:14…                    ┆ TGGCT…                    ┆ IIIGIG…                  │
│ SRR9130495.3  ┆ D00236:723:HG32CBCX2:1:11 ┆ GTTTTCCTCTGGTTATTTCTAGGTA ┆ @@@DDDFFHHHFHBHIIGJIJIIJ │
│               ┆ 08:17…                    ┆ CACTG…                    ┆ IIIEHG…                  │
│ SRR9130495.4  ┆ D00236:723:HG32CBCX2:1:11 ┆ GGGAGGCGCCCCGACCGGCCAGGGC ┆ CCCFFFFFHHHHGHIIIGIIJIII │
│               ┆ 08:16…                    ┆ GTGAG…                    ┆ JJGHFF…                  │
│ SRR9130495.5  ┆ D00236:723:HG32CBCX2:1:11 ┆ CACTCCGCCACTACAGCAGTCCCCC ┆ ++=A1A:1ADA<;FFDC?;CG<F; │
│               ┆ 08:16…                    ┆ AGTGT…                    ┆ ::1CFI…                  │
│ SRR9130495.6  ┆ D00236:723:HG32CBCX2:1:11 ┆ CGATAAAGGACTTTCAGTCAACCAA ┆ CC@DDDBDFFHHHJJIJJIIJIJJ │
│               ┆ 08:23…                    ┆ CTAGA…                    ┆ JIIIHG…                  │
│ SRR9130495.7  ┆ D00236:723:HG32CBCX2:1:11 ┆ TGGCAATGGTGTTTCTTCTTATATG ┆ @CCFFFFFHHHHHIGIJJIJIJJJ │
│               ┆ 08:35…                    ┆ ATGCT…                    ┆ IJJJJJ…                  │
│ SRR9130495.8  ┆ D00236:723:HG32CBCX2:1:11 ┆ TATTTCTTACTCTTTCAGATGTTAC ┆ CCCFFFFFHHHHHJJJJGGIIJIJ │
│               ┆ 08:37…                    ┆ CCTCC…                    ┆ JHGJJJ…                  │
│ SRR9130495.9  ┆ D00236:723:HG32CBCX2:1:11 ┆ NAAACTTTGATGTCCTAGCCCCAGG ┆ #4=DFDFFHHHHHIJJJHGIIIJJ │
│               ┆ 08:39…                    ┆ AGATG…                    ┆ JJGIIJ…                  │
│ SRR9130495.10 ┆ D00236:723:HG32CBCX2:1:11 ┆ CTGTCAGTACAGTGGGACCCACAGA ┆ B@@DDBDFDFHHC<F<BGHGBFHG │
│               ┆ 08:37…                    ┆ ACAGA…                    ┆ IJIGEG…                  │
└───────────────┴───────────────────────────┴───────────────────────────┴──────────────────────────┘

In [5]:
pb.sql("select avg(length(sequence)) as read_length from example").collect()

0rows [00:00, ?rows/s]

shape: (1, 1)
┌─────────────┐
│ read_length │
│ ---         │
│ f64         │
╞═════════════╡
│ 101.0       │
└─────────────┘

In [6]:
pb.get_sequence_quality_stats("example")

example

TypeError: py_run_and_register_base_quality() missing 1 required positional argument: 'table'